[package]
name = "ed25519-zebra"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/ZcashFoundation/ed25519-zebra"
description = "Zcash-flavored Ed25519 for use in Zebra."

[package.metadata.docs.rs]
features = ["nightly"]

[dependencies]
rand_core = "0.5"
thiserror = "1"
curve25519-dalek = "2"
serde = { version = "1", optional = true, features = ["derive"] }

[features]
nightly = []
default = ["serde"]
